### ISSUE TITLE
Permissions Migrations

### ISSUE THREAD

**Issue by djamesfar** [tipoff/test-support#20]
- bump dependency of tipoff/authorization to 2.5.0
- Verify all permissions in the policies are included in the package permissions migration
- Add arrays after every permission in that migration except delete to include the ‘Owner’ role
- Also add the ‘Staff’ role to the array for every view permission

example from the Fees package:
```
    public function up()
    {
        $permissions = [
             'view fees' => ['Owner', 'Staff'],
             'create fees' => ['Owner'],
             'update fees' => ['Owner'],
             'delete fees' => [],   // Admin only
        ];

        $this->createPermissions($permissions);
    }

**Comment by drewroberts** [comment]
This issue does not apply to the test support package. There may be a way to do a better job of testing the migrated permissions though and making sure they are assigned to roles.
